services:
  # app:
  #   container_name: curriculo-app
  #   build: .
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - PORT=${PORT}
  #     - DATABASE_HOST=${DATABASE_HOST}
  #     - DATABASE_PORT=${DATABASE_PORT}
  #     - DATABASE_USERNAME=${DATABASE_USERNAME}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_NAME=${DATABASE_NAME}
  #     - DATABASE_URL=postgresql://curriculo:123456@postgres:5432/curriculo_db
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - ${PORT}:3000
  #   command: yarn generate & yarn start:dev
  #   depends_on:
  #     - postgres
  #   networks:
  #     - mynetwork

  postgres:
    image: postgres:16.1-alpine
    restart: always
    container_name: curriculo-postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - mynetwork

volumes:
  boilerplate-db:

networks:
  mynetwork:
    driver: bridge
