FROM node:20-alpine

# Defina o diretório de trabalho no container
WORKDIR /usr/src/app

# Copie o arquivo package.json e yarn.lock (se disponível)
COPY package.json yarn.lock ./

# Instale as dependências do projeto
RUN yarn install

# Copie o restante dos arquivos do projeto
COPY . .

RUN yarn prisma generate

# Exponha a porta que o app usa (altere para a porta correta do seu app)
EXPOSE 8080

# Comando para iniciar o app
CMD [ "yarn", "start:dev" ]