services:
  # app:
  #   container_name: curriculo-app
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - ${PORT}:8080
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:16.1-alpine
    container_name: curriculo-postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  boilerplate-db:
